#!/usr/bin/env python

import sys
import os

import yaml
from brome import Brome

from configs.selector import selector_dict
from configs.test_dict import test_dict

if __name__ == '__main__':

    HERE = os.path.abspath(os.path.dirname(__file__))

    # BROWSERS CONFIG
    browsers_config_path = os.path.join(HERE, "configs", "browsers_config.yml")
    with open(browsers_config_path) as fd:
        browsers_config = yaml.load(fd)

    # BROME CONFIG
    brome_config_path = os.path.join(HERE, "configs", "brome.yml")
    with open(brome_config_path) as fd:
        config = yaml.load(fd)

    brome = Brome(
        config=config,
        selector_dict=selector_dict,
        test_dict=test_dict,
        browsers_config=browsers_config,
        absolute_path=HERE
    )

    brome.execute(sys.argv)
